spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_demo?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password: biao123
    hikari:
      readOnly: false
      connectionTimeout: 30000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 120000
      loginTimeout: 5
      maximumPoolSize: 100
      minimumIdle: 10
      connection-test-query: select 1