spring:
  shardingsphere:
    datasource:
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
      names: master,slave1,slave2
      master:
        jdbc-url: jdbc:mysql://localhost:3316/demo_master?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
      slave1:
        jdbc-url: jdbc:mysql://localhost:3316/demo_slave_0?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
      slave2:
        jdbc-url: jdbc:mysql://localhost:3316/demo_slave_1?useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
    rules:
      replica-query:
        data-sources:
          ds:
            primary-data-source-name: master
            replica-data-source-names: slave1,slave2
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              defaule: 0
    props:
      sql-show: true
mybatis:
  mapper-locations: mapper/*.xml